name: teste_webhook
#
on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Hello World
        run: echo "Hello World"
    
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - uses: actions/checkout@v3
      - name: Hello World
        run: cat arquivo.txt

  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - uses: actions/checkout@v3
      - name: Hello World
        run: echo "Hello World"
